config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'pages#home'

  devise_for :users
  resources :quotes
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
# frozen_string_literal: true

class Company < ApplicationRecord
    has_many :users, dependent: :destroy
    has_many :quotes, dependent: :destroy

    validates :name, presence: true
end

app/models/quote.rb
# frozen_string_literal: true

class Quote < ApplicationRecord
    belongs_to :company

    validates :name, presence: true

    scope :ordered, -> { order(id: :desc) }

    broadcasts_to ->(quote) { [ quote.company, 'quotes' ] }, inserts_by: :prepend
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :validatable

  belongs_to :company

  def name
    email.split('@').first.capitalize
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
    before_action :authenticate_user!, unless: :devise_controller?

    def current_company
        @current_company ||= current_user.company if user_signed_in?
    end
    helper_method :current_company
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end
end

app/controllers/quotes_controller.rb
# frozen_string_literal: true

class QuotesController < ApplicationController
    before_action :set_quote, only: [ :show, :edit, :update, :destroy ]

    def index
        @quotes = current_company.quotes.ordered
    end

    def show; end

    def new
        @quote = Quote.new
    end

    def create
        @quote = current_company.quotes.build(quote_params)

        if @quote.save!
            success_response
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit; end

    def update
        if @quote.update(quote_params)
            success_response
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @quote.destroy

        success_response
    end

    private

    def set_quote
        @quote = current_company.quotes.find(params[:id])
    end

    def quote_params
        params.require(:quote).permit(:name)
    end

    def success_response
        respond_to do |format|
            format.html { redirect_to quotes_path, notice: t('.success_notice') }
            format.turbo_stream { flash.now[:notice] = t('.success_notice') }
        end
    end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
def render_turbo_stream_flash_messages
    turbo_stream.prepend 'flash', partial: 'layouts/flash'
    end
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/quotes_helper.rb
# frozen_string_literal: true

module QuotesHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div
    class="flash__message"
    data-controller="removals"
    data-action="animationend->removals#remove"
>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="navbar">
  <% if user_signed_in? %>
    <div class="navbar__brand">
      <%= current_company.name %>
    </div>
    <div class="navbar__name">
      <%= current_user.name %>
    </div>
    <%= button_to t('sign_out_button'),
                  destroy_user_session_path,
                  method: :delete,
                  class: "btn btn--dark" %>
  <% else %>
    <%= link_to t('sign_in_button'),
                new_user_session_path,
                class: "btn btn--dark navbar__right" %>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuoteEditor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar" %>

    <div id="flash" class="flash">
      <%= render "layouts/flash" %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<main class="container">
  <h1><%= t('.title') %></h1>
  <p><%= t('.subtitle') %></p>

  <% if user_signed_in? %>
    <%= link_to t('.quotes_button'), quotes_path, class: "btn btn--dark" %>
  <% else %>
    <%= link_to t('sign_in_button'), new_user_session_path, class: "btn btn--dark" %>
  <% end %>
</main>

app/views/quotes/_back_button.html.erb
  <%= link_to sanitize(t('quotes.back_button')), quotes_path %>

app/views/quotes/_form.html.erb
<%= simple_form_for quote, html: { class: 'quote form' }  do |f| %>
    <% if quote.errors.any? %>
        <div class="error-message">
            <%= quote.errors.full_messages.to_sentence.capitalize %>
        </div>
    <% end %>

    <%= f.input :name, input_html: { autofocus: true } %>
    <%= link_to t('cancel_button'), quotes_path, class: 'btn btn--light' %>
    <%= f.submit class: 'btn btn--secondary' %>
<% end %>

app/views/quotes/_quote.html.erb
<%= turbo_frame_tag quote do %>
    <div class="quote">
        <%= link_to quote.name, quote_path(quote), data: { turbo_frame: '_top' } %>
        <div class="quote__actions">
            <%= button_to t('delete_button'), quote_path(quote), method: :delete, class: 'btn btn--light', form: { data: { turbo_frame: '_top' } } %>
            <%= link_to t('edit_button'), edit_quote_path(quote), class: 'btn btn--light' %>
        </div>
    </div>
<% end %>

app/views/quotes/create.turbo_stream.erb
<%= turbo_stream.prepend 'quotes', @quote %>
<%= turbo_stream.update Quote.new, "" %>
<%= render_turbo_stream_flash_messages %>

app/views/quotes/destroy.turbo_stream.erb
<%= turbo_stream.remove @quote %>

app/views/quotes/edit.html.erb
<main class="container">
      <%= render 'back_button' %>

    <div class="header">
        <h1><%= t('.title') %></h1>
    </div>

    <%= turbo_frame_tag @quote do %>
        <%= render 'form', quote: @quote %>
    <% end %>
</main>

app/views/quotes/index.html.erb
<%= turbo_stream_from current_company, "quotes" %>

<main class="container">
    <div class="header">
        <h1><%= t('.title') %></h1>
        <%= link_to t('.new_button'), new_quote_path, class: 'btn btn--primary', data: { turbo_frame: dom_id(Quote.new) } %>
    </div>

    <%= turbo_frame_tag Quote.new %>

    <%= turbo_frame_tag 'quotes' do %>
        <%= render @quotes %>
    <% end %>
</main>

app/views/quotes/new.html.erb
<main class="container">
      <%= render 'back_button' %>

    <div class="header">
        <h1><%= t('.title') %></h1>
    </div>

    <%= turbo_frame_tag @quote do %>
        <%= render 'form', quote: @quote %>
    <% end %>
</main>

app/views/quotes/show.html.erb
<main class="container">
  <%= render 'back_button' %>

  <div class="header">
    <h1>
      <%= @quote.name %>
    </h1>
  </div>
</main>

app/views/quotes/update.turbo_stream.erb
<%= turbo_stream.replace @quote %>
<%= render_turbo_stream_flash_messages %>